### ISSUE TITLE
Coordinar visita al Museu

### ISSUE THREAD

**Issue by jsanz** [geocamp-es/2019#4]
Correo enviado para la coordinación con las instalaciones del Museu Comarcal de l'Horta Sud Josep Ferrandis. 

http://museuhortasud.com

**Comment by Manalemart** [comment]
Como habéis quedado al final? Los sábados estan abiertos tambien la gente del museu. Por si os viene mejor

**Comment by jsanz** [comment]
el sábado @raolbaletco y un servidor visitamos el Museu, estaban tanto Clara que nos dio la visita como Marta.

Nos enseñaron las instalaciones y llegamos a las siguientes conclusiones:

* A priori pensamos en usar la sala del sótano, habrá una exposición e acuarelas, en cualquier caso habrá sillas de plástico para poder estar también fuera si hiciera buen tiempo
* Tenemos disponbilidad también de la sala de la Andana, que tiene un espacio para unas 20 personas y otra sala más pequeña para unas 8.
* En la sala de abajo hay un espacio separado donde la gente podría sentarse a trabajar (aunque igual podrían molestar)
* No hay problema en llevar catering
* El espacio es totalmente accesible para gente con mobilidad reducida
* No hay aire acondicionado, pero tienen ventiladores
* Tienen regletas, proyector, y habrá una televisión (del Ayuntamiento) para proyectar en el patio si lo necesitamos
* Nos han pasado una lista de lugares para comer, habría que avisarles
* Nos han pasado logos para la web y nos pasarán material gráfico para usarlo en la web o en merch si lo hacemos
* Si tras las rondas iniciales de inscripción quedan plazas libres, les podemos pasar una nota de prensa para que le den difusión ellas
* Sin problema para acabar sobre las 7pm
  * ¿Y a qué hora empezamos? Para este sábado empezaron a las 10.

Fotos de los alrededores del Museu en [esta carpeta](https://drive.google.com/drive/folders/171XrV6gDfmQf7b24s7Ar8BoadcRvQDdt?usp=sharing)

**Comment by jsanz** [comment]
@raolbaletco si me dejo algo métele aunque cierre ya la tarea.
