### ISSUE TITLE
Redes sociales

### ISSUE THREAD

**Issue by jsanz** [geocamp-es/2019#8]
* Hootsuite o Tweetdeck para programarlos
* Hacer banner nuevo para la portada de Twitter
* Facebook no se usa desde 2017
* Nos concentramos solo en Twitter

Tareas

* [x] Crear un spreadsheet con tweets propuestos
* [x] Arreglar banner
* [x] Empezar a twittear fechas y tal

**Comment by jsanz** [comment]
@All4Gis nos pasas el background o el editable del banner del año pasado para reutilizarlo?

**Comment by jsanz** [comment]
@sliob he actualizado el perfil para que salga la fecha de la geocamp y quitado el banner

![image](https://user-images.githubusercontent.com/188264/56763174-06ebf280-67a2-11e9-8d53-c1420e5160ec.png)

**Comment by All4Gis** [comment]
Te refieres a estos https://github.com/geocamp-es/2018/tree/master/assets/img/svg @jsanz ?

**Comment by jsanz** [comment]
me refería al banner que se usó en twitter pero no te preocupes, @sliob ya está montando algo justo con el material que subiste en SVG. ¡Gracias jefe!

**Comment by sliob** [comment]
![image](https://user-images.githubusercontent.com/11195544/56871591-7a9b3300-6a20-11e9-8402-50b2556d8e41.png)
Ya he cambiado el banner del Twitter de Geocamp y he twitteado un "SAVE THE DATE!"

He creado un spreadsheet y lo he compartido con vosotros. Id poniendo textos para twitter y ya iré twiteandolos.
