### ISSUE TITLE
Montar meetup

### ISSUE THREAD

**Issue by jsanz** [geocamp-es/2019#9]
* [ ] Crear el meetup de la geocamp con contenidos que tenemos.
* [ ] Definir qué hacemos con la geopaella (nos mandan un correo y au?)

**Comment by Manalemart** [comment]
Yo pondría un meetup aparte para la geopaella, asi controlamos la gente interesada que pueda no estar en la geocampes. Y tal vez poner un precio de reservar por lo mismo de siempre.

**Comment by jsanz** [comment]
Cierto que puede haber gente que venga  a la geopaella, pero entonces tenemos doble comisión para paypal :disappointed:

**Comment by Manalemart** [comment]
> Cierto que puede haber gente que venga a la geopaella, pero entonces tenemos doble comisión para paypal 😞

La otra es poner dos precios de registro... 5 euros para el evento y 10€¿? para la geopaella (a descontar de lo que tenga que pagar la gente ese dia por ejemplo?? ). Nose, es por que la gente se bloquee ese dia y poder dar una buena estimación a Descubre l'Horta.

**Comment by jsanz** [comment]
Eso no se puede hacer con meetup :(

**Comment by jsanz** [comment]
vale acordamos montar un meetup ya para la geocamp y dejamos el tema de la geopaella totalmente aparte en una página dedicada (con paypal para que la gente se registre pagando una parte)
